# 服务器配置
server:
  host: "0.0.0.0"
  port: 8080
  mode: "debug"  # debug, release, test
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 60

# 数据库配置
database:
  host: "text-audit-mysql"
  port: 3306
  user: "root"
  password: "root123"
  dbname: "text_audit"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

# Redis配置
redis:
  host: "text-audit-redis"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: 5
  read_timeout: 3
  write_timeout: 3
  pool_timeout: 4
  idle_timeout: 300

# 模型配置
model:
  base_path: "/app/models"
  max_loaded_models: 5
  load_timeout: 300
  cache_ttl: 3600

# 推理配置
inference:
  max_batch_size: 100
  timeout: 30
  cache_ttl: 300
  max_concurrent_requests: 50

# 日志配置
logging:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, text
  output: "stdout"  # stdout, stderr, file
  file_path: "/var/log/model-inference.log"
  max_size: 100  # MB
  max_backups: 5
  max_age: 30  # days
  compress: true