# Data Collector Service Production Configuration

# HTTP Server Configuration
http:
  address: ":8080"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

# gRPC Server Configuration
grpc:
  address: ":9090"
  max_recv_msg_size: 4194304  # 4MB
  max_send_msg_size: 4194304  # 4MB

# Database Configuration
database:
  host: "mysql"
  port: 3306
  username: "ai_user"
  password: "ai_pass123"
  database: "ai_demo"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600s

# Redis Configuration
redis:
  address: "redis:6379"
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

# Kafka Configuration
kafka:
  brokers:
    - "kafka:9092"
  raw_topic: "raw_text"
  processed_topic: "processed_text"
  consumer_group: "data-collector"
  batch_size: 100
  batch_timeout: 1s

# MinIO Configuration
minio:
  endpoint: "minio:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin123"
  bucket: "ai-demo-data"
  use_ssl: false

# Collector Configuration
collector:
  rate_limit: 10  # 每秒请求数
  concurrent_limit: 5  # 并发数
  timeout: 60s
  max_retries: 3
  retry_delay: 5s
  
  # 知乎专用配置
  zhihu:
    enabled: true
    rate_limit: 5  # 知乎更严格的限制
    concurrent_limit: 2
    delay_range: "2s-5s"  # 随机延迟范围
    max_pages: 50  # 最大翻页数
    
    # User-Agent池
    user_agents:
      - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
      - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
      - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
      - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15"
      - "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/120.0"
    
    # 代理配置（可选）
    proxies: []
    
    # Cookie存储路径
    cookie_file: "/app/data/cookies/zhihu_cookies.json"
    
    # 内容过滤
    filters:
      min_length: 50  # 最小内容长度
      max_length: 10000  # 最大内容长度
      exclude_patterns:
        - "广告"
        - "推广"
        - "spam"
      
    # 采集目标配置
    targets:
      questions:
        selectors:
          - ".QuestionHeader-title"
          - ".QuestionRichText"
        max_count: 1000
      
      answers:
        selectors:
          - ".RichContent-inner"
        min_vote_count: 10  # 最小点赞数
        max_count: 2000
      
      search:
        selectors:
          - ".SearchResult-Card"
        max_count: 500
      
      topics:
        selectors:
          - ".ContentItem"
        max_count: 1000

# 日志配置
logging:
  level: "debug"
  format: "json"
  output: "stdout"
  file:
    enabled: true
    path: "/app/logs/collector.log"
    max_size: 100  # MB
    max_backups: 10
    max_age: 30  # days
    compress: true

# 监控配置
monitoring:
  enabled: true
  metrics_port: 9080
  health_check_interval: 30s
  
  # Prometheus指标
  prometheus:
    enabled: true
    path: "/metrics"
    
  # 性能指标
  performance:
    track_request_duration: true
    track_collection_stats: true
    track_error_rates: true

# 安全配置
security:
  # API密钥（如果需要）
  api_keys: []
  
  # IP白名单（如果需要）
  allowed_ips: []
  
  # 请求头验证
  required_headers: []

# 数据存储配置
storage:
  # 本地存储
  local:
    enabled: true
    base_path: "/app/data"
    
  # 对象存储
  object:
    enabled: true
    bucket: "ai-demo-raw-data"
    
  # 数据库存储
  database:
    enabled: true
    batch_size: 100
    batch_timeout: 5s

# 数据质量配置
quality:
  # 去重配置
  deduplication:
    enabled: true
    hash_algorithm: "sha256"
    similarity_threshold: 0.9
    
  # 内容验证
  validation:
    enabled: true
    min_words: 10
    max_words: 5000
    language_detection: true
    
  # 数据清洗
  cleaning:
    enabled: true
    remove_html: true
    normalize_whitespace: true
    remove_urls: false
    remove_emails: false